// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFiles() {
  return window['go']['main']['App']['AddFiles']();
}

export function AddPaths(arg1) {
  return window['go']['main']['App']['AddPaths'](arg1);
}

export function ChangeIcon(arg1) {
  return window['go']['main']['App']['ChangeIcon'](arg1);
}

export function ConvertToAbsolute() {
  return window['go']['main']['App']['ConvertToAbsolute']();
}

export function ConvertToRelative() {
  return window['go']['main']['App']['ConvertToRelative']();
}

export function GetData() {
  return window['go']['main']['App']['GetData']();
}

export function Launch(arg1) {
  return window['go']['main']['App']['Launch'](arg1);
}

export function PickDirectory(arg1) {
  return window['go']['main']['App']['PickDirectory'](arg1);
}

export function PickFile(arg1) {
  return window['go']['main']['App']['PickFile'](arg1);
}

export function Reveal(arg1) {
  return window['go']['main']['App']['Reveal'](arg1);
}

export function SaveData(arg1) {
  return window['go']['main']['App']['SaveData'](arg1);
}

export function Stop(arg1) {
  return window['go']['main']['App']['Stop'](arg1);
}

export function UpdateIcon(arg1) {
  return window['go']['main']['App']['UpdateIcon'](arg1);
}
