// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFiles():Promise<main.AddResult>;

export function AddPaths(arg1:Array<string>):Promise<main.AddResult>;

export function ChangeIcon(arg1:string):Promise<main.IconResult>;

export function GetData():Promise<main.AppData>;

export function Launch(arg1:string):Promise<void>;

export function Reveal(arg1:string):Promise<void>;

export function SaveData(arg1:main.AppStore):Promise<void>;

export function Stop(arg1:string):Promise<void>;

export function UpdateIcon(arg1:string):Promise<main.IconResult>;
