// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFiles() {
  return window['go']['main']['App']['AddFiles']();
}

export function AddPaths(arg1) {
  return window['go']['main']['App']['AddPaths'](arg1);
}

export function ChangeIcon(arg1) {
  return window['go']['main']['App']['ChangeIcon'](arg1);
}

export function Details(arg1) {
  return window['go']['main']['App']['Details'](arg1);
}

export function GetItems() {
  return window['go']['main']['App']['GetItems']();
}

export function Launch(arg1) {
  return window['go']['main']['App']['Launch'](arg1);
}

export function RemoveItem(arg1) {
  return window['go']['main']['App']['RemoveItem'](arg1);
}

export function RenameItem(arg1, arg2) {
  return window['go']['main']['App']['RenameItem'](arg1, arg2);
}

export function Reveal(arg1) {
  return window['go']['main']['App']['Reveal'](arg1);
}

export function Stop(arg1) {
  return window['go']['main']['App']['Stop'](arg1);
}

export function UpdateIcon(arg1) {
  return window['go']['main']['App']['UpdateIcon'](arg1);
}
