// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFiles():Promise<void>;

export function AddPaths(arg1:Array<string>):Promise<void>;

export function ChangeIcon(arg1:string):Promise<void>;

export function Details(arg1:string):Promise<string>;

export function GetAutoMinimize():Promise<boolean>;

export function GetItems():Promise<Array<main.LauncherItemView>>;

export function Launch(arg1:string):Promise<void>;

export function MoveItem(arg1:number,arg2:number):Promise<void>;

export function RemoveItem(arg1:string):Promise<void>;

export function RenameItem(arg1:string,arg2:string):Promise<void>;

export function Reveal(arg1:string):Promise<void>;

export function SetAutoMinimize(arg1:boolean):Promise<void>;

export function Stop(arg1:string):Promise<void>;

export function UpdateIcon(arg1:string):Promise<void>;
